### ISSUE TITLE
Add a modal for the form error

### ISSUE THREAD

**Issue by rishavb123** [theHackSB/thehacksb.github.io#3]
This does not matter as much. For now, I am using an alert.

**Comment by Swapnil-N** [comment]
Add an error message if all parts of the form are not filled out except the diet textbox, an X button in the top right to close it and more options for food preference

**Comment by SethuSenthil** [comment]
Z index is working so the snack bar isn't showing up, I also added an alert until we fix this

**Comment by SethuSenthil** [comment]
This bug was long fixed
